spring:
  mail:
    host: smtp.gmail.com
    username: ajsantos5d@gmail.com
    password: 96979044aJ!
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true